[build]
command = "CI=false npm run build"
publish = "build"

[build.environment]
CI = "false"
GENERATE_SOURCEMAP = "false"
NODE_VERSION = "18"

# Netlify Functions - Simple configuration
[functions]
directory = "functions"

# Redirects for SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
