[build]
base = "frontend"
command = "CI=false npm run build"
publish = "build"

[build.environment]
CI = "false"
GENERATE_SOURCEMAP = "false"

# Netlify Functions
[functions]
directory = "netlify/functions"
