[build]
base = "frontend"
command = "CI=false npm run build"
publish = "build"

[build.environment]
CI = "false"
GENERATE_SOURCEMAP = "false"
NODE_VERSION = "18"

# Netlify Functions - Moved to frontend directory
[functions]
directory = "functions"
node_bundler = "esbuild"

# Redirects for SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
